name: 'BrowserStack Test'
on: [push, pull_request]
jobs:
  ubuntu-job:
    name: 'BrowserStack Test on Ubuntu'
    runs-on: ubuntu-latest  # Can be self-hosted runner also
    steps:

      - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      - name: 'Checkout the repository'
        uses: actions/checkout@v2
      - uses: actions/setup-node@v5
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Update browserstack.yml with secrets
        run: |
          sed -i 's/userName: .*/userName: ${{ secrets.BROWSERSTACK_USERNAME }}/' browserstack.yml
          sed -i 's/accessKey: .*/accessKey: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}/' browserstack.yml
      - name: Run Playwright tests
        run: npm run bstack  
        # The next 3 steps are for building the web application to be tested and starting the web server on the runner environment
 # See sample test script above

